services:
  web:
    build: .
    restart: unless-stopped
    networks:
      - default
      - caddy
    labels:
      caddy: mcapi.cf12.org
      caddy.reverse_proxy: "{{upstreams 8080}}"

  redis:
    image: "redis:alpine"
    restart: unless-stopped
    networks:
      - default

networks:
  caddy:
    external: true
