services:
  web:
    build: .
    restart: unless-stopped
    networks:
      - caddy
    labels:
      caddy: mcapi.cf12.org
      caddy.reverse_proxy: "{{upstreams}}"
  redis:
    image: "redis:alpine"

networks:
  caddy:
    external: true
